[package]
name = "merkletree-rs"
version = "0.0.1"
authors = ["arnaucube <arnaucube@gmail.com>"]

[dependencies]
tiny-keccak = "1.4.2"
rustc-hex = "1.0.0"
bitreader = "0.3.1"
arrayref = "0.3.5"
byteorder = "1.3.1"
hex = "0.3.2"
